<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void
    {
        Schema::create('brands', function (Blueprint $t) { $t->id(); $t->string('name'); $t->string('slug')->unique(); $t->text('description')->nullable(); $t->text('short_description')->nullable(); $t->string('logo')->nullable(); $t->string('cover_image')->nullable(); $t->string('website_url')->nullable(); $t->string('meta_title')->nullable(); $t->text('meta_description')->nullable(); $t->boolean('is_active')->default(true)->index(); $t->unsignedInteger('sort_order')->default(0); $t->timestamps(); $t->softDeletes(); });
        Schema::create('categories', function (Blueprint $t) { $t->id(); $t->foreignId('parent_id')->nullable()->constrained('categories')->nullOnDelete(); $t->string('name'); $t->string('slug')->unique(); $t->text('description')->nullable(); $t->string('image')->nullable(); $t->string('meta_title')->nullable(); $t->text('meta_description')->nullable(); $t->boolean('is_active')->default(true)->index(); $t->unsignedInteger('sort_order')->default(0); $t->timestamps(); $t->softDeletes(); });
        Schema::create('collections', function (Blueprint $t) { $t->id(); $t->foreignId('brand_id')->nullable()->constrained()->nullOnDelete(); $t->string('name'); $t->string('slug')->unique(); $t->text('description')->nullable(); $t->text('short_description')->nullable(); $t->string('hero_image')->nullable(); $t->string('banner_image')->nullable(); $t->boolean('is_featured')->default(false)->index(); $t->boolean('is_active')->default(true)->index(); $t->unsignedInteger('sort_order')->default(0); $t->string('meta_title')->nullable(); $t->text('meta_description')->nullable(); $t->timestamps(); $t->softDeletes(); });
        Schema::create('product_families', function (Blueprint $t) { $t->id(); $t->foreignId('brand_id')->nullable()->constrained()->nullOnDelete(); $t->foreignId('collection_id')->nullable()->constrained()->nullOnDelete(); $t->string('name'); $t->string('slug')->unique(); $t->text('description')->nullable(); $t->string('hero_image')->nullable(); $t->boolean('is_active')->default(true)->index(); $t->unsignedInteger('sort_order')->default(0); $t->timestamps(); $t->softDeletes(); });
        foreach (['materials', 'finishes'] as $table) Schema::create($table, function (Blueprint $t) { $t->id(); $t->string('name'); $t->string('slug')->unique(); $t->text('description')->nullable(); $t->string('image')->nullable(); $t->boolean('is_active')->default(true)->index(); $t->unsignedInteger('sort_order')->default(0); $t->timestamps(); });
        Schema::create('colors', function (Blueprint $t) { $t->id(); $t->string('name'); $t->string('slug')->unique(); $t->string('hex_code', 16)->nullable(); $t->string('image')->nullable(); $t->boolean('is_active')->default(true)->index(); $t->unsignedInteger('sort_order')->default(0); $t->timestamps(); });
        foreach (['tags', 'features'] as $table) Schema::create($table, function (Blueprint $t) { $t->id(); $t->string('name'); $t->string('slug')->unique(); $t->text('description')->nullable(); $t->boolean('is_active')->default(true)->index(); $t->unsignedInteger('sort_order')->default(0); $t->timestamps(); });
        Schema::create('products', function (Blueprint $t) { $t->id(); $t->foreignId('brand_id')->constrained()->restrictOnDelete(); $t->foreignId('category_id')->constrained()->restrictOnDelete(); $t->foreignId('collection_id')->nullable()->constrained()->nullOnDelete(); $t->foreignId('product_family_id')->nullable()->constrained()->nullOnDelete(); $t->string('name'); $t->string('slug')->unique(); $t->string('sku')->unique(); $t->text('short_description')->nullable(); $t->longText('description')->nullable(); $t->json('specifications')->nullable(); $t->text('care_instructions')->nullable(); $t->text('assembly_information')->nullable(); $t->text('warranty_information')->nullable(); $t->string('status')->default('draft')->index(); $t->string('product_type')->nullable()->index(); $t->boolean('is_featured')->default(false)->index(); $t->boolean('is_new')->default(false)->index(); $t->boolean('is_bestseller')->default(false)->index(); $t->boolean('is_customizable')->default(false); $t->boolean('is_active')->default(true)->index(); $t->unsignedInteger('sort_order')->default(0); $t->string('meta_title')->nullable(); $t->text('meta_description')->nullable(); $t->timestamps(); $t->softDeletes(); });
        Schema::create('options', function (Blueprint $t) { $t->id(); $t->string('name')->unique(); $t->string('slug')->unique(); $t->unsignedInteger('sort_order')->default(0); $t->timestamps(); });
        Schema::create('option_values', function (Blueprint $t) { $t->id(); $t->foreignId('option_id')->constrained()->cascadeOnDelete(); $t->string('value'); $t->string('slug'); $t->unsignedInteger('sort_order')->default(0); $t->timestamps(); $t->unique(['option_id', 'value']); $t->unique(['option_id', 'slug']); });
        Schema::create('product_variants', function (Blueprint $t) { $t->id(); $t->foreignId('product_id')->constrained()->cascadeOnDelete(); $t->string('sku')->unique(); $t->string('name')->nullable(); $t->string('barcode')->nullable()->unique(); $t->decimal('price_override', 12, 2)->nullable(); $t->decimal('cost_price', 12, 2)->nullable(); $t->decimal('weight', 10, 3)->nullable(); $t->string('weight_unit', 12)->nullable(); $t->string('status')->default('draft')->index(); $t->boolean('is_default')->default(false)->index(); $t->boolean('is_active')->default(true)->index(); $t->timestamps(); $t->softDeletes(); });
        Schema::create('product_options', function (Blueprint $t) { $t->id(); $t->foreignId('product_id')->constrained()->cascadeOnDelete(); $t->foreignId('option_id')->constrained()->cascadeOnDelete(); $t->unsignedInteger('sort_order')->default(0); $t->boolean('is_required')->default(false); $t->timestamps(); $t->unique(['product_id','option_id']); });
        Schema::create('product_variant_options', function (Blueprint $t) { $t->id(); $t->foreignId('product_variant_id')->constrained()->cascadeOnDelete(); $t->foreignId('option_value_id')->constrained()->cascadeOnDelete(); $t->timestamps(); $t->unique(['product_variant_id','option_value_id']); });
        Schema::create('product_images', function (Blueprint $t) { $t->id(); $t->foreignId('product_id')->constrained()->cascadeOnDelete(); $t->foreignId('product_variant_id')->nullable()->constrained()->cascadeOnDelete(); $t->string('path'); $t->string('alt_text')->nullable(); $t->string('title')->nullable(); $t->string('type')->default('gallery')->index(); $t->unsignedInteger('sort_order')->default(0); $t->boolean('is_primary')->default(false)->index(); $t->json('metadata')->nullable(); $t->timestamps(); });
        Schema::create('product_videos', function (Blueprint $t) { $t->id(); $t->foreignId('product_id')->constrained()->cascadeOnDelete(); $t->foreignId('product_variant_id')->nullable()->constrained()->cascadeOnDelete(); $t->string('url'); $t->string('title')->nullable(); $t->string('thumbnail')->nullable(); $t->unsignedInteger('sort_order')->default(0); $t->timestamps(); });
        Schema::create('product_documents', function (Blueprint $t) { $t->id(); $t->foreignId('product_id')->constrained()->cascadeOnDelete(); $t->string('type')->index(); $t->string('title'); $t->string('path'); $t->timestamps(); });
        foreach (['product_dimensions' => 'product_id', 'variant_dimensions' => 'product_variant_id'] as $table => $key) Schema::create($table, function (Blueprint $t) use ($key) { $t->id(); $t->foreignId($key)->constrained()->cascadeOnDelete(); $t->decimal('width',10,2)->nullable(); $t->decimal('depth',10,2)->nullable(); $t->decimal('height',10,2)->nullable(); $t->decimal('seat_height',10,2)->nullable(); $t->decimal('seat_depth',10,2)->nullable(); $t->decimal('arm_height',10,2)->nullable(); $t->decimal('clearance',10,2)->nullable(); $t->decimal('weight',10,3)->nullable(); $t->string('dimension_unit',12)->default('cm'); $t->string('weight_unit',12)->default('kg'); $t->string('label')->nullable(); $t->timestamps(); });
        Schema::create('rooms', function (Blueprint $t) { $t->id(); $t->string('name'); $t->string('slug')->unique(); $t->text('description')->nullable(); $t->string('image')->nullable(); $t->boolean('is_active')->default(true)->index(); $t->unsignedInteger('sort_order')->default(0); $t->timestamps(); });
        foreach (['category_product'=>'category_id','collection_product'=>'collection_id','material_product'=>'material_id','finish_product'=>'finish_id','color_product'=>'color_id','tag_product'=>'tag_id','feature_product'=>'feature_id','room_product'=>'room_id'] as $table=>$left) Schema::create($table, function(Blueprint $t) use($left) { $t->foreignId($left)->constrained()->cascadeOnDelete(); $t->foreignId('product_id')->constrained()->cascadeOnDelete(); if ($left === 'room_id') $t->unsignedInteger('sort_order')->default(0); $t->timestamps(); $t->unique([$left,'product_id']); });
        Schema::create('color_product_variant', function (Blueprint $t) { $t->foreignId('color_id')->constrained()->cascadeOnDelete(); $t->foreignId('product_variant_id')->constrained()->cascadeOnDelete(); $t->timestamps(); $t->unique(['color_id','product_variant_id']); });
        Schema::create('related_products', function (Blueprint $t) { $t->id(); $t->foreignId('product_id')->constrained()->cascadeOnDelete(); $t->foreignId('related_product_id')->constrained('products')->cascadeOnDelete(); $t->string('relationship_type')->default('similar'); $t->unsignedInteger('sort_order')->default(0); $t->timestamps(); $t->unique(['product_id','related_product_id','relationship_type']); });
        Schema::create('warehouses', function (Blueprint $t) { $t->id(); $t->string('name'); $t->string('code')->unique(); $t->string('phone')->nullable(); $t->string('email')->nullable(); $t->string('address_line_1')->nullable(); $t->string('address_line_2')->nullable(); $t->string('city')->nullable(); $t->string('state')->nullable(); $t->string('postal_code')->nullable(); $t->string('country',2)->nullable(); $t->boolean('is_active')->default(true)->index(); $t->timestamps(); });
        Schema::create('inventories', function (Blueprint $t) { $t->id(); $t->foreignId('warehouse_id')->constrained()->cascadeOnDelete(); $t->foreignId('product_variant_id')->constrained()->cascadeOnDelete(); $t->integer('quantity_on_hand')->default(0); $t->integer('quantity_reserved')->default(0); $t->integer('reorder_level')->default(0); $t->timestamps(); $t->unique(['warehouse_id','product_variant_id']); });
        Schema::create('stock_movements', function (Blueprint $t) { $t->id(); $t->foreignId('inventory_id')->constrained()->cascadeOnDelete(); $t->integer('quantity'); $t->string('movement_type')->index(); $t->nullableMorphs('reference'); $t->text('notes')->nullable(); $t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete(); $t->timestamps(); });
        Schema::create('prices', function (Blueprint $t) { $t->id(); $t->foreignId('product_id')->constrained()->cascadeOnDelete(); $t->foreignId('product_variant_id')->nullable()->constrained()->cascadeOnDelete(); $t->decimal('amount',12,2); $t->string('currency',3); $t->string('price_type')->default('retail')->index(); $t->timestamp('starts_at')->nullable()->index(); $t->timestamp('ends_at')->nullable()->index(); $t->boolean('is_active')->default(true)->index(); $t->timestamps(); });
        Schema::create('promotions', function (Blueprint $t) { $t->id(); $t->string('name'); $t->string('code')->nullable()->unique(); $t->text('description')->nullable(); $t->string('discount_type'); $t->decimal('discount_value',12,2); $t->foreignId('product_id')->nullable()->constrained()->nullOnDelete(); $t->foreignId('category_id')->nullable()->constrained()->nullOnDelete(); $t->foreignId('collection_id')->nullable()->constrained()->nullOnDelete(); $t->timestamp('starts_at')->nullable()->index(); $t->timestamp('ends_at')->nullable()->index(); $t->boolean('is_active')->default(true)->index(); $t->timestamps(); });
        Schema::create('wishlists', function (Blueprint $t) { $t->id(); $t->foreignId('user_id')->constrained()->cascadeOnDelete(); $t->string('name')->nullable(); $t->timestamps(); });
        Schema::create('wishlist_items', function (Blueprint $t) { $t->id(); $t->foreignId('wishlist_id')->constrained()->cascadeOnDelete(); $t->foreignId('product_id')->constrained()->cascadeOnDelete(); $t->foreignId('product_variant_id')->nullable()->constrained()->nullOnDelete(); $t->timestamps(); $t->unique(['wishlist_id','product_id','product_variant_id']); });
        Schema::create('addresses', function (Blueprint $t) { $t->id(); $t->foreignId('user_id')->constrained()->cascadeOnDelete(); $t->string('first_name'); $t->string('last_name'); $t->string('company')->nullable(); $t->string('phone'); $t->string('address_line_1'); $t->string('address_line_2')->nullable(); $t->string('city'); $t->string('state'); $t->string('postal_code')->nullable(); $t->string('country',2); $t->boolean('is_default')->default(false)->index(); $t->timestamps(); });
        Schema::create('carts', function (Blueprint $t) { $t->id(); $t->foreignId('user_id')->nullable()->constrained()->nullOnDelete(); $t->string('session_id')->nullable()->index(); $t->string('status')->default('active')->index(); $t->timestamps(); $t->index(['user_id','status']); });
        Schema::create('cart_items', function (Blueprint $t) { $t->id(); $t->foreignId('cart_id')->constrained()->cascadeOnDelete(); $t->foreignId('product_id')->constrained()->restrictOnDelete(); $t->foreignId('product_variant_id')->nullable()->constrained()->nullOnDelete(); $t->unsignedInteger('quantity'); $t->decimal('unit_price',12,2); $t->timestamps(); $t->unique(['cart_id','product_id','product_variant_id']); });
        Schema::create('orders', function (Blueprint $t) { $t->id(); $t->foreignId('user_id')->nullable()->constrained()->nullOnDelete(); $t->string('order_number')->unique(); $t->string('status')->default('pending')->index(); $t->string('currency',3); $t->decimal('subtotal',12,2)->default(0); $t->decimal('discount_total',12,2)->default(0); $t->decimal('shipping_total',12,2)->default(0); $t->decimal('tax_total',12,2)->default(0); $t->decimal('grand_total',12,2)->default(0); foreach (['billing','shipping'] as $prefix) { $t->string("{$prefix}_first_name"); $t->string("{$prefix}_last_name"); $t->string("{$prefix}_company")->nullable(); $t->string("{$prefix}_phone"); $t->string("{$prefix}_address_line_1"); $t->string("{$prefix}_address_line_2")->nullable(); $t->string("{$prefix}_city"); $t->string("{$prefix}_state"); $t->string("{$prefix}_postal_code")->nullable(); $t->string("{$prefix}_country",2); } $t->timestamps(); });
        Schema::create('order_items', function (Blueprint $t) { $t->id(); $t->foreignId('order_id')->constrained()->cascadeOnDelete(); $t->foreignId('product_id')->nullable()->constrained()->nullOnDelete(); $t->foreignId('product_variant_id')->nullable()->constrained()->nullOnDelete(); $t->string('sku'); $t->string('product_name'); $t->string('variant_name')->nullable(); $t->unsignedInteger('quantity'); $t->decimal('unit_price',12,2); $t->decimal('discount_amount',12,2)->default(0); $t->decimal('total',12,2); $t->json('metadata')->nullable(); $t->timestamps(); });
        Schema::create('reviews', function (Blueprint $t) { $t->id(); $t->foreignId('user_id')->constrained()->cascadeOnDelete(); $t->foreignId('product_id')->constrained()->cascadeOnDelete(); $t->unsignedTinyInteger('rating'); $t->string('title')->nullable(); $t->text('body'); $t->string('status')->default('pending')->index(); $t->boolean('verified_purchase')->default(false); $t->timestamps(); $t->index(['product_id','status']); });
        Schema::create('lookbooks', function (Blueprint $t) { $t->id(); $t->string('title'); $t->string('slug')->unique(); $t->text('description')->nullable(); $t->string('hero_image')->nullable(); $t->string('status')->default('draft')->index(); $t->timestamp('published_at')->nullable()->index(); $t->timestamps(); });
        Schema::create('lookbook_items', function (Blueprint $t) { $t->id(); $t->foreignId('lookbook_id')->constrained()->cascadeOnDelete(); $t->foreignId('product_id')->constrained()->cascadeOnDelete(); $t->string('image')->nullable(); $t->string('title')->nullable(); $t->text('description')->nullable(); $t->unsignedInteger('sort_order')->default(0); $t->timestamps(); $t->unique(['lookbook_id','product_id']); });
        Schema::create('banners', function (Blueprint $t) { $t->id(); $t->string('title'); $t->string('subtitle')->nullable(); $t->string('image'); $t->string('mobile_image')->nullable(); $t->string('link')->nullable(); $t->string('link_type')->nullable(); $t->string('placement')->index(); $t->timestamp('starts_at')->nullable()->index(); $t->timestamp('ends_at')->nullable()->index(); $t->boolean('is_active')->default(true)->index(); $t->unsignedInteger('sort_order')->default(0); $t->timestamps(); });
        Schema::create('featured_collections', function (Blueprint $t) { $t->id(); $t->foreignId('collection_id')->constrained()->cascadeOnDelete(); $t->string('placement')->index(); $t->unsignedInteger('sort_order')->default(0); $t->timestamp('starts_at')->nullable(); $t->timestamp('ends_at')->nullable(); $t->boolean('is_active')->default(true)->index(); $t->timestamps(); $t->unique(['collection_id','placement']); });
        Schema::create('featured_products', function (Blueprint $t) { $t->id(); $t->foreignId('product_id')->constrained()->cascadeOnDelete(); $t->string('placement')->index(); $t->unsignedInteger('sort_order')->default(0); $t->timestamp('starts_at')->nullable(); $t->timestamp('ends_at')->nullable(); $t->boolean('is_active')->default(true)->index(); $t->timestamps(); $t->unique(['product_id','placement']); });
        Schema::create('pages', function (Blueprint $t) { $t->id(); $t->string('title'); $t->string('slug')->unique(); $t->longText('content')->nullable(); $t->string('meta_title')->nullable(); $t->text('meta_description')->nullable(); $t->string('status')->default('draft')->index(); $t->timestamp('published_at')->nullable()->index(); $t->timestamps(); });
        Schema::create('page_sections', function (Blueprint $t) { $t->id(); $t->foreignId('page_id')->constrained()->cascadeOnDelete(); $t->string('type'); $t->json('configuration')->nullable(); $t->unsignedInteger('sort_order')->default(0); $t->timestamps(); });
        Schema::create('faqs', function (Blueprint $t) { $t->id(); $t->string('question'); $t->text('answer'); $t->string('category')->nullable()->index(); $t->boolean('is_active')->default(true)->index(); $t->unsignedInteger('sort_order')->default(0); $t->timestamps(); });
    }
    public function down(): void
    {
        foreach (['faqs','page_sections','pages','featured_products','featured_collections','banners','lookbook_items','lookbooks','reviews','order_items','orders','cart_items','carts','addresses','wishlist_items','wishlists','promotions','prices','stock_movements','inventories','warehouses','related_products','color_product_variant','room_product','feature_product','tag_product','color_product','finish_product','material_product','collection_product','category_product','rooms','variant_dimensions','product_dimensions','product_documents','product_videos','product_images','product_variant_options','product_options','product_variants','option_values','options','products','features','tags','colors','finishes','materials','product_families','collections','categories','brands'] as $table) Schema::dropIfExists($table);
    }
};
